export const ZEROX_ALLOWANCE_HOLDER =
  "0x0000000000001fF3684f28c67538d4D072C22734" as const

export const JUPITER_V6_PROGRAM_ID =
  "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4" as const

export const SOLANA_USDC_MINT =
  "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" as const

export {
  sessionSpend7702Abi,
  SESSION_SPEND_NAME,
  SESSION_SPEND_VERSION,
  EVM_NATIVE_TOKEN,
  ZEROX_NATIVE_TOKEN,
  GasFundingMode,
  RelayAction,
  sessionSpendDomain,
  swapBundleIntentV2Types,
  swapBundleIntentV2Domain,
  relayDepositIntentTypes,
  creditRelayAssetIntentTypes,
  remoteRelaySellIntentTypes,
  creditUsdcReturnIntentTypes,
  releaseRelayDepositIntentTypes,
  restoreRemoteRelayAssetIntentTypes,
  relayGasTopUpIntentTypes,
  releaseRelayGasTopUpIntentTypes,
  relayDepositIntentDomain,
  creditRelayAssetIntentDomain,
  remoteRelaySellIntentDomain,
  creditUsdcReturnIntentDomain,
  releaseRelayDepositIntentDomain,
  restoreRemoteRelayAssetIntentDomain,
  relayGasTopUpIntentDomain,
  releaseRelayGasTopUpIntentDomain,
  walletRelaySwapIntentTypes,
  walletRelaySwapIntentDomain,
  hashRelayCalldata,
  normalizeRelayOrderId,
  strategyVaultSalt,
  strategyVaultAddress,
  encodeSessionGrant,
  encodeSessionRevoke,
  encodeSessionSignedRevoke,
  encodeSessionRotate,
  encodeSessionSetLimit,
  encodeExecuteSwapWithFeesV2,
  encodeExecuteRelayDeposit,
  encodeCreditRelayAsset,
  encodeExecuteRemoteRelaySell,
  encodeExecuteRelayGasTopUp,
  encodeReleaseRelayGasTopUp,
  encodeExecuteWalletRelaySwap,
  encodeCreditUsdcReturn,
  encodeReleaseRelayDeposit,
  encodeRestoreRemoteRelayAsset,
  encodeSetPlatformRelayer,
  encodeRecoverVaultSurplus,
  strategyIdFromCuid,
  revokeIntentTypes,
} from "./evm/session-spend-7702"

export {
  WALLET_SEED,
  STRATEGY_SEED,
  VAULT_SEED,
  ASSET_SEED,
  AUTHORITY_SEED,
  RELAY_RECEIPT_SEED,
  RELAY_PENDING_DEPOSIT_SEED,
  RELAY_PENDING_SELL_SEED,
  RELAY_PENDING_GAS_SEED,
  REMOTE_ASSET_SEED,
  REMOTE_AGGREGATE_SEED,
  NATIVE_VAULT_SEED,
  RelayAction as SolanaRelayAction,
  strategyPda,
  vaultPda,
  assetPda,
  walletPda,
  authorityPda,
  relayReceiptPda,
  relayPendingDepositPda,
  relayPendingSellPda,
  relayPendingGasTopUpPda,
  remoteAssetPda,
  remoteAggregatePda,
  nativeVaultPda,
  encodeInitWallet,
  encodeInitStrategy,
  encodeSetLimit,
  encodeRotateSession,
  encodeRevoke,
  encodeExecuteSwapWithFees as encodeSolanaExecuteSwapWithFees,
  encodeExecuteRelayDeposit as encodeSolanaExecuteRelayDeposit,
  encodeCreditRelayAsset as encodeSolanaCreditRelayAsset,
  encodeExecuteRemoteRelaySell as encodeSolanaExecuteRemoteRelaySell,
  encodeCreditUsdcReturn as encodeSolanaCreditUsdcReturn,
  encodeReleaseRelayDeposit as encodeSolanaReleaseRelayDeposit,
  encodeRestoreRemoteRelayAsset as encodeSolanaRestoreRemoteRelayAsset,
  encodeExecuteRelayGasTopUp as encodeSolanaExecuteRelayGasTopUp,
  encodeReleaseRelayGasTopUp as encodeSolanaReleaseRelayGasTopUp,
  encodeWithdrawAsset,
  encodeCloseStrategy,
  solanaStrategyIdFromCuid,
} from "./solana/strategy-spend"

export type { SolanaGasMode, InitWalletAccounts } from "./solana/strategy-spend"

export type {
  RevokeIntentMessage,
  SwapBundleIntentV2Message,
  RelayDepositIntentMessage,
  CreditRelayAssetIntentMessage,
  RemoteRelaySellIntentMessage,
  CreditUsdcReturnIntentMessage,
  ReleaseRelayDepositIntentMessage,
  RestoreRemoteRelayAssetIntentMessage,
  RelayGasTopUpIntentMessage,
  ReleaseRelayGasTopUpIntentMessage,
  WalletRelaySwapIntentMessage,
} from "./evm/session-spend-7702"
